
import os
from pdf_generator import generate_pdf
from datetime import datetime
from agents.swot_agent import SWOTAgent
from agents.market_agent import MarketResearchAgent
from agents.competitor_agent import CompetitorAgent
from agents.business_agent import BusinessAgent
from agents.risk_agent import RiskAgent
from agents.mvp_agent import MVPAgent
from agents.scoring_agent import ScoringAgent
from agents.executive_summary_agent import ExecutiveSummaryAgent
from agents.financial_agent import FinancialProjectionAgent
# Get startup idea
startup_idea = input("Enter your startup idea: ")

# Initialize agents
market = MarketResearchAgent()
competitor = CompetitorAgent()
business = BusinessAgent()
risk = RiskAgent()
mvp = MVPAgent()
score = ScoringAgent()
executive_summary_agent = ExecutiveSummaryAgent()
swot = SWOTAgent()
financial = FinancialProjectionAgent()
print("\nGenerating AI Startup Co-Founder Report...\n")

# Generate reports
market_report = market.analyze(startup_idea)
competitor_report = competitor.analyze(startup_idea)
business_report = business.analyze(startup_idea)
risk_report = risk.analyze(startup_idea)
mvp_report = mvp.analyze(startup_idea)

score_report = score.analyze(startup_idea)

executive_summary = executive_summary_agent.analyze(startup_idea)
swot_report = swot.analyze(startup_idea)
financial_report = financial.analyze(startup_idea)
# Timestamps
report_timestamp = datetime.now().strftime("%d-%m-%Y %H:%M:%S")
file_timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

# Final report
final_report = f"""
AI STARTUP CO-FOUNDER REPORT

REPORT TYPE: AI Startup Co-Founder Analysis
GENERATED BY: Multi-Agent AI Analysis Platform
MODEL: DeepSeek Chat V3 (via OpenRouter)
VERSION: 1.0
GENERATED ON: {report_timestamp}

==================================================
EXECUTIVE SUMMARY
==================================================

{executive_summary}

==================================================
STARTUP IDEA
==================================================

{startup_idea}

==================================================
MARKET RESEARCH
==================================================

{market_report}

==================================================
COMPETITOR ANALYSIS
==================================================

{competitor_report}

==================================================
BUSINESS STRATEGY
==================================================

{business_report}

==================================================
RISK ASSESSMENT
==================================================

{risk_report}

==================================================
SWOT ANALYSIS
==================================================

{swot_report}

==================================================
MVP ROADMAP
==================================================

==================================================
FINANCIAL PROJECTIONS
==================================================

{financial_report}

{mvp_report}

==================================================
STARTUP SCORE & INVESTMENT DECISION
==================================================

{score_report}

==================================================
FINAL VERDICT
==================================================

Based on the market opportunity, competition, business model,
risk profile, and MVP feasibility, this startup has been
evaluated using a multi-agent AI analysis framework.

Recommended Next Steps:

1. Validate the idea with real customers
2. Conduct interviews and gather feedback
3. Build and launch the MVP
4. Measure user adoption and retention
5. Iterate based on customer feedback
6. Prepare investor materials if traction is achieved

==================================================
END OF REPORT
==================================================
"""

# Create reports directory
os.makedirs("reports", exist_ok=True)
os.makedirs("reports/agents", exist_ok=True)

# Save individual agent outputs
with open("reports/agents/market_report.txt", "w", encoding="utf-8") as f:
    f.write(market_report)

with open("reports/agents/competitor_report.txt", "w", encoding="utf-8") as f:
    f.write(competitor_report)

with open("reports/agents/business_report.txt", "w", encoding="utf-8") as f:
    f.write(business_report)

with open("reports/agents/risk_report.txt", "w", encoding="utf-8") as f:
    f.write(risk_report)

with open("reports/agents/mvp_report.txt", "w", encoding="utf-8") as f:
    f.write(mvp_report)

with open("reports/agents/score_report.txt", "w", encoding="utf-8") as f:
    f.write(score_report)

with open("reports/agents/executive_summary.txt", "w", encoding="utf-8") as f:
    f.write(executive_summary)

with open("reports/agents/swot_report.txt", "w", encoding="utf-8") as f:
    f.write(swot_report)

with open("reports/agents/financial_report.txt", "w", encoding="utf-8") as f:
    f.write(financial_report)

# Save final report
filename = f"reports/startup_report_{file_timestamp}.txt"

with open(filename, "w", encoding="utf-8") as file:
    file.write(final_report)
    
pdf_filename = f"reports/startup_report_{file_timestamp}.pdf"

generate_pdf(final_report, pdf_filename)

print("Report generated successfully!")
print(f"TXT Report: {filename}")
print(f"PDF Report: {pdf_filename}")
